version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://magic8ball:secretpassword@db:5432/magic_eight_ball
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - magic8ball-network

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=magic_eight_ball
      - POSTGRES_USER=magic8ball
      - POSTGRES_PASSWORD=secretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U magic8ball -d magic_eight_ball"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - magic8ball-network

volumes:
  postgres_data:

networks:
  magic8ball-network:
    driver: bridge 